In [1]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\lenovo\anaconda3\lib\site-packages (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging<25,>=20 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.4.26)
Requirement already satisfied: attrs>=22.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)

In [2]:
pip install streamlit pandas numpy scikit-learn plotly matplotlib seaborn

Requirement already satisfied: streamlit in c:\users\lenovo\anaconda3\lib\site-packages (1.45.1)
Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\lenovo\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: scikit-learn in c:\users\lenovo\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: plotly in c:\users\lenovo\anaconda3\lib\site-packages (5.24.1)
Requirement already satisfied: matplotlib in c:\users\lenovo\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: seaborn in c:\users\lenovo\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: altair<6,>=4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (8.1.8)
Requirement already satisfied: packaging<25,>=20 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (24.2)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: jinja2 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.4.26)
Requirement already satisfied: scipy>=1.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [48]:
pip install streamlit-option-menu

Collecting streamlit-option-menuNote: you may need to restart the kernel to use updated packages.

  Downloading streamlit_option_menu-0.4.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: streamlit>=1.36 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit-option-menu) (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (2.1.3)
Requirement already satisfied: packaging<25,>=20 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (6.5.1)
Requirement already satisfied: jinja2 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (1.31.0)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit>=1.36->streamlit-option-menu) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2025.4.26)
Requirement already satisfied: attrs>=22.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.22.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.2)
Downloading streamlit_option_menu-0.4.0-py3-none-any.whl (829 kB)
   ---------------------------------------- 0.0/829.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/829.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/829.3 kB ? eta -:--:--
   ------------ --------------------------- 262.1/829.3 kB ? eta -:--:--
   ------------------------ ------------- 524.3/829.3 kB 994.3 kB/s eta 0:00:01
   ------------------------ ------------- 524.3/829.3 kB 994.3 kB/s eta 0:00:01
   ------------------------------------ - 786.4/829.3 kB 689.7 kB/s eta 0:00:01
   -------------------------------------- 829.3/829.3 kB 675.4 kB/s eta 0:00:00
Installing collected packages: streamlit-option-menu
Successfully installed streamlit-option-menu-0.4.0

In [3]:
import pandas as pd

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("C:\\3rd year\\2 semester\\ST 3011\\GrpWork\\LFS-2023-25-Percent-Data-Without-Computer.csv")
df.head()

,YEAR,MONTH,SECTOR,DISTRICT,PSU,HUNIT,HHOLD,SERNO,RSHIP,SEX,...,Q63_A_22,Q63_A_3,Q63_A_42,Q63_A_5,Q63_B_22,Q63_B_3,Q63_B_42,Q63_B_5,Q64,Annual_Factor
0,2023,1,1,11,1,2,1,1,1,2,...,,,,,,,,,2,1309.608564
1,2023,1,1,11,1,2,1,2,2,1,...,,,,,,,,,3,1309.608564
2,2023,1,1,11,1,6,1,1,1,1,...,,,,,,,,,2,1309.608564
3,2023,1,1,11,1,6,1,2,2,2,...,,,,,,,,,2,1309.608564
4,2023,1,1,11,1,6,1,3,3,1,...,,,,,,,,,10,1309.608564

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18937 entries, 0 to 18936
Columns: 128 entries, YEAR to Annual_Factor
dtypes: float64(1), int64(21), object(106)
memory usage: 18.5+ MB

In [7]:
df.shape

(18937, 128)

In [8]:
required_cols = [
    'MONTH',
    'SECTOR', 'DISTRICT', 'PSU', 'HUNIT', 'HHOLD', 'SERNO',
    'SEX', 'BYEAR', 'BMONTH', 'AGE',
    'EDU', 'CUEDU', 'P21',
    'Q2', 'Q4', 'Q6_A',
    'Q47', 'Q48', 'Q50', 'Q51', 'Q52'
]

df = df[required_cols].copy()

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18937 entries, 0 to 18936
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MONTH     18937 non-null  int64
 1   SECTOR    18937 non-null  int64
 2   DISTRICT  18937 non-null  int64
 3   PSU       18937 non-null  int64
 4   HUNIT     18937 non-null  int64
 5   HHOLD     18937 non-null  int64
 6   SERNO     18937 non-null  int64
 7   SEX       18937 non-null  int64
 8   BYEAR     18937 non-null  int64
 9   BMONTH    18937 non-null  object
 10  AGE       18937 non-null  int64
 11  EDU       18937 non-null  object
 12  CUEDU     18937 non-null  object
 13  P21       18937 non-null  object
 14  Q2        18937 non-null  object
 15  Q4        18937 non-null  object
 16  Q6_A      18937 non-null  object
 17  Q47       18937 non-null  object
 18  Q48       18937 non-null  object
 19  Q50       18937 non-null  object
 20  Q51       18937 non-null  object
 21  Q52       18937 non-null  object
dtypes: int64(10), object(12)
memory usage: 3.2+ MB

In [10]:
#Convert questionnaire variables to numeric
survey_cols = [
    'BMONTH', 'EDU', 'CUEDU', 'P21',
    'Q2', 'Q4', 'Q6_A',
    'Q47', 'Q48', 'Q50', 'Q51', 'Q52'
]

for col in survey_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18937 entries, 0 to 18936
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MONTH     18937 non-null  int64
 1   SECTOR    18937 non-null  int64
 2   DISTRICT  18937 non-null  int64
 3   PSU       18937 non-null  int64
 4   HUNIT     18937 non-null  int64
 5   HHOLD     18937 non-null  int64
 6   SERNO     18937 non-null  int64
 7   SEX       18937 non-null  int64
 8   BYEAR     18937 non-null  int64
 9   BMONTH    18732 non-null  float64
 10  AGE       18937 non-null  int64
 11  EDU       17918 non-null  float64
 12  CUEDU     17918 non-null  float64
 13  P21       15230 non-null  float64
 14  Q2        15230 non-null  float64
 15  Q4        8466 non-null   float64
 16  Q6_A      8177 non-null   float64
 17  Q47       8177 non-null   float64
 18  Q48       500 non-null    float64
 19  Q50       208 non-null    float64
 20  Q51       500 non-null    float64
 21  Q52       7699 non-null   float64
dtypes: float64(12), int64(10)
memory usage: 3.2 MB

In [12]:
df_youth = df[(df['AGE'] >= 15) & (df['AGE'] <= 29)].copy()

In [13]:
df_youth.shape

(3949, 22)

In [14]:
def derive_employment_status(row):
    # Employed
    if (row['Q2'] == 1) or (row['Q4'] == 1) or (row['Q6_A'] == 1):
        return 'Employed'

    # Unemployed
    elif (row['Q48'] == 1) and (row['Q51'] == 1):
        return 'Unemployed'

    # Not in Labour Force
    else:
        return 'Not in Labour Force'

In [15]:
df_youth['employment_status'] = df_youth.apply(
    derive_employment_status, axis=1
)

In [16]:
df_youth['employment_status'].value_counts()

employment_status
Not in Labour Force    2521
Employed               1239
Unemployed              189
Name: count, dtype: int64

In [17]:
#Recode SECTOR
df_youth['SECTOR'] = df_youth['SECTOR'].map({
    1: 'Urban',
    2: 'Rural',
    3: 'Estate'
}).astype('category')

In [18]:
#Recode District
district_labels = {
    11: 'Colombo', 12: 'Gampaha', 13: 'Kalutara',
    21: 'Kandy', 22: 'Matale', 23: 'Nuwara Eliya',
    31: 'Galle', 32: 'Matara', 33: 'Hambantota',
    41: 'Jaffna', 42: 'Mannar', 43: 'Vavuniya',
    44: 'Mullaitivu', 45: 'Kilinochchi',
    51: 'Batticaloa', 52: 'Ampara', 53: 'Trincomalee',
    61: 'Kurunegala', 62: 'Puttalam',
    71: 'Anuradhapura', 72: 'Polonnaruwa',
    81: 'Badulla', 82: 'Monaragala',
    91: 'Ratnapura', 92: 'Kegalle'
}

df_youth['DISTRICT'] = df_youth['DISTRICT'].map(district_labels).astype('category')

In [19]:
#Recode SEX
df_youth['SEX'] = df_youth['SEX'].map({
    1: 'Male',
    2: 'Female'
}).astype('category')

In [20]:
#Recode EDU
edu_labels = {
    0.0: 'Studying / Studied Grade 1',
    1.0: 'Passed Grade 1',
    2.0: 'Passed Grade 2',
    3.0: 'Passed Grade 3',
    4.0: 'Passed Grade 4',
    5.0: 'Passed Grade 5' ,
    6.0: 'Passed Grade 6',
    7.0: 'Passed Grade 7',
    8.0: 'Passed Grade 8',
    9.0: 'Passed Grade 9',
    10.0: 'Passed Grade 10',
    11.0: 'Passed G.C.E.(O/L)/ N.C.G.E. ',
    12.0: 'Passed Grade 12',
    13.0:' Passed G.C.E.(A/L)/ H.N.C.E. ',
    14.0: 'Passed G.A.Q./G.S.Q.' ,
    15.0: 'Degree ',
    16.0: 'Post Graduate Degree/ Diploma ',
    17.0: 'Special educational Institutions',
    19.0: 'No Schooling'
}

df_youth['EDU'] = df_youth['EDU'].map(edu_labels).astype('category')

In [21]:
#Recode CUEDU
cuedu_labels = {
    1: 'School',
    2: 'University',
    3: 'Other Educational Institution',
    4: 'Vocational / Technical Institution',
    5: 'Does not attend'
}

df_youth['CUEDU'] = df_youth['CUEDU'].map(cuedu_labels).astype('category')

In [22]:
#Recode P21
df_youth['P21'] = df_youth['P21'].map({
    1: 'Currently studying/training',
    2: 'Not studying'
}).astype('category')

In [23]:
df_youth.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3949 entries, 1 to 18930
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   MONTH              3949 non-null   int64
 1   SECTOR             3949 non-null   category
 2   DISTRICT           3949 non-null   category
 3   PSU                3949 non-null   int64
 4   HUNIT              3949 non-null   int64
 5   HHOLD              3949 non-null   int64
 6   SERNO              3949 non-null   int64
 7   SEX                3949 non-null   category
 8   BYEAR              3949 non-null   int64
 9   BMONTH             3926 non-null   float64
 10  AGE                3949 non-null   int64
 11  EDU                3949 non-null   category
 12  CUEDU              3949 non-null   category
 13  P21                3949 non-null   category
 14  Q2                 3949 non-null   float64
 15  Q4                 2812 non-null   float64
 16  Q6_A               2784 non-null   float64
 17  Q47                2784 non-null   float64
 18  Q48                349 non-null    float64
 19  Q50                137 non-null    float64
 20  Q51                349 non-null    float64
 21  Q52                2449 non-null   float64
 22  employment_status  3949 non-null   object
dtypes: category(6), float64(9), int64(7), object(1)
memory usage: 580.5+ KB

In [24]:
df_youth.head()

,MONTH,SECTOR,DISTRICT,PSU,HUNIT,HHOLD,SERNO,SEX,BYEAR,BMONTH,...,P21,Q2,Q4,Q6_A,Q47,Q48,Q50,Q51,Q52,employment_status
1,1,Urban,Colombo,1,2,1,2,Male,1993,4.0,...,Not studying,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed
4,1,Urban,Colombo,1,6,1,3,Male,2003,3.0,...,Not studying,2.0,2.0,2.0,2.0,NaN,NaN,NaN,4.0,Not in Labour Force
5,1,Urban,Colombo,1,6,1,4,Male,2006,3.0,...,Currently studying/training,2.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,Not in Labour Force
9,1,Urban,Colombo,1,10,1,2,Male,2007,7.0,...,Currently studying/training,2.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,Not in Labour Force
15,1,Urban,Colombo,2,8,1,2,Female,1999,11.0,...,Not studying,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed

In [25]:
df_youth['employment_status'] = df_youth['employment_status'].astype('category')

df_youth['employment_status'].cat.categories

Index(['Employed', 'Not in Labour Force', 'Unemployed'], dtype='object')

In [26]:
df_youth.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3949 entries, 1 to 18930
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   MONTH              3949 non-null   int64
 1   SECTOR             3949 non-null   category
 2   DISTRICT           3949 non-null   category
 3   PSU                3949 non-null   int64
 4   HUNIT              3949 non-null   int64
 5   HHOLD              3949 non-null   int64
 6   SERNO              3949 non-null   int64
 7   SEX                3949 non-null   category
 8   BYEAR              3949 non-null   int64
 9   BMONTH             3926 non-null   float64
 10  AGE                3949 non-null   int64
 11  EDU                3949 non-null   category
 12  CUEDU              3949 non-null   category
 13  P21                3949 non-null   category
 14  Q2                 3949 non-null   float64
 15  Q4                 2812 non-null   float64
 16  Q6_A               2784 non-null   float64
 17  Q47                2784 non-null   float64
 18  Q48                349 non-null    float64
 19  Q50                137 non-null    float64
 20  Q51                349 non-null    float64
 21  Q52                2449 non-null   float64
 22  employment_status  3949 non-null   category
dtypes: category(7), float64(9), int64(7)
memory usage: 553.6 KB

In [27]:
df_youth.isnull().sum()

MONTH                   0
SECTOR                  0
DISTRICT                0
PSU                     0
HUNIT                   0
HHOLD                   0
SERNO                   0
SEX                     0
BYEAR                   0
BMONTH                 23
AGE                     0
EDU                     0
CUEDU                   0
P21                     0
Q2                      0
Q4                   1137
Q6_A                 1165
Q47                  1165
Q48                  3600
Q50                  3812
Q51                  3600
Q52                  1500
employment_status       0
dtype: int64

In [28]:
df_youth.duplicated().sum()

np.int64(0)

In [29]:
df_youth_full = df_youth.copy()

df_youth_full['employment_status'].value_counts()

employment_status
Not in Labour Force    2521
Employed               1239
Unemployed              189
Name: count, dtype: int64

In [30]:
df_lf = df_youth_full[
    df_youth_full['employment_status'].isin(['Employed', 'Unemployed'])
].copy()

df_lf['employment_status'].value_counts()

employment_status
Employed               1239
Unemployed              189
Not in Labour Force       0
Name: count, dtype: int64

In [31]:
df_youth_full.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3949 entries, 1 to 18930
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   MONTH              3949 non-null   int64
 1   SECTOR             3949 non-null   category
 2   DISTRICT           3949 non-null   category
 3   PSU                3949 non-null   int64
 4   HUNIT              3949 non-null   int64
 5   HHOLD              3949 non-null   int64
 6   SERNO              3949 non-null   int64
 7   SEX                3949 non-null   category
 8   BYEAR              3949 non-null   int64
 9   BMONTH             3926 non-null   float64
 10  AGE                3949 non-null   int64
 11  EDU                3949 non-null   category
 12  CUEDU              3949 non-null   category
 13  P21                3949 non-null   category
 14  Q2                 3949 non-null   float64
 15  Q4                 2812 non-null   float64
 16  Q6_A               2784 non-null   float64
 17  Q47                2784 non-null   float64
 18  Q48                349 non-null    float64
 19  Q50                137 non-null    float64
 20  Q51                349 non-null    float64
 21  Q52                2449 non-null   float64
 22  employment_status  3949 non-null   category
dtypes: category(7), float64(9), int64(7)
memory usage: 553.6 KB

In [32]:
df_lf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1428 entries, 1 to 18900
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   MONTH              1428 non-null   int64
 1   SECTOR             1428 non-null   category
 2   DISTRICT           1428 non-null   category
 3   PSU                1428 non-null   int64
 4   HUNIT              1428 non-null   int64
 5   HHOLD              1428 non-null   int64
 6   SERNO              1428 non-null   int64
 7   SEX                1428 non-null   category
 8   BYEAR              1428 non-null   int64
 9   BMONTH             1418 non-null   float64
 10  AGE                1428 non-null   int64
 11  EDU                1428 non-null   category
 12  CUEDU              1428 non-null   category
 13  P21                1428 non-null   category
 14  Q2                 1428 non-null   float64
 15  Q4                 291 non-null    float64
 16  Q6_A               263 non-null    float64
 17  Q47                263 non-null    float64
 18  Q48                214 non-null    float64
 19  Q50                12 non-null     float64
 20  Q51                214 non-null    float64
 21  Q52                48 non-null     float64
 22  employment_status  1428 non-null   category
dtypes: category(7), float64(9), int64(7)
memory usage: 201.6 KB

In [33]:
#Export youth population dataset
df_youth_full.to_csv("youth_population.csv", index=False)

In [34]:
#Export labour force dataset
df_lf.to_csv("youth_labour_force.csv", index=False)

In [33]:
#unemp_youth = df_lf[df_lf['employment_status'] == 'Unemployed']

In [35]:
def recode_edu(edu):
    edu = str(edu).strip()

    # Primary or Below
    if edu in [
        'No Schooling',
        'Studying / Studied Grade 1',
        'Passed Grade 1',
        'Passed Grade 2',
        'Passed Grade 3',
        'Passed Grade 4',
        'Passed Grade 5'
    ]:
        return 'Grade 5 or Below'

    # Junior Secondary
    elif edu in [
        'Passed Grade 6',
        'Passed Grade 7',
        'Passed Grade 8',
        'Passed Grade 9',
        'Passed Grade 10'
    ]:
        return 'Grade 6-10'

    # Secondary (O/L)
    elif edu in [
        'Passed G.C.E.(O/L)/ N.C.G.E.'
    ]:
        return 'G.C.E.(O/L)'

    # Senior Secondary (A/L)
    elif edu in [
        'Passed Grade 12',
        'Passed G.C.E.(A/L)/ H.N.C.E.'
    ]:
        return 'G.C.E.(A/L)'

    else:
        return 'Degree / Education institue'

In [36]:
df_lf['EDU_group'] = df_lf['EDU'].apply(recode_edu)
df_lf[['EDU', 'EDU_group','employment_status']].head(20)

,EDU,EDU_group,employment_status
1,Passed G.C.E.(A/L)/ H.N.C.E.,G.C.E.(A/L),Employed
15,Degree,Degree / Education institue,Employed
20,Passed G.C.E.(A/L)/ H.N.C.E.,G.C.E.(A/L),Employed
29,Passed G.C.E.(A/L)/ H.N.C.E.,G.C.E.(A/L),Employed
48,Passed Grade 10,Grade 6-10,Employed
49,Passed Grade 9,Grade 6-10,Employed
55,Passed Grade 10,Grade 6-10,Employed
56,Passed Grade 10,Grade 6-10,Employed
76,Passed Grade 10,Grade 6-10,Employed
83,Passed Grade 10,Grade 6-10,Employed
84,Passed G.C.E.(O/L)/ N.C.G.E.,G.C.E.(O/L),Unemployed
111,Passed G.C.E.(A/L)/ H.N.C.E.,G.C.E.(A/L),Employed
114,Passed Grade 10,Grade 6-10,Employed
128,Passed G.C.E.(A/L)/ H.N.C.E.,G.C.E.(A/L),Unemployed
133,Passed G.C.E.(A/L)/ H.N.C.E.,G.C.E.(A/L),Employed
169,Passed G.C.E.(A/L)/ H.N.C.E.,G.C.E.(A/L),Employed
175,Passed G.C.E.(A/L)/ H.N.C.E.,G.C.E.(A/L),Unemployed
192,Passed G.C.E.(A/L)/ H.N.C.E.,G.C.E.(A/L),Employed
201,Passed G.C.E.(O/L)/ N.C.G.E.,G.C.E.(O/L),Employed
207,Passed Grade 12,G.C.E.(A/L),Employed

In [37]:
######### Create PROVINCE from DISTRICT

district_to_province = {
    # Western
    'Colombo': 'Western', 'Gampaha': 'Western', 'Kalutara': 'Western',

    # Central
    'Kandy': 'Central', 'Matale': 'Central', 'Nuwara Eliya': 'Central',

    # Southern
    'Galle': 'Southern', 'Matara': 'Southern', 'Hambantota': 'Southern',

    # Northern
    'Jaffna': 'Northern', 'Kilinochchi': 'Northern', 'Mannar': 'Northern',
    'Mullaitivu': 'Northern', 'Vavuniya': 'Northern',

    # Eastern
    'Trincomalee': 'Eastern', 'Batticaloa': 'Eastern', 'Ampara': 'Eastern',

    # North Western
    'Kurunegala': 'North Western', 'Puttalam': 'North Western',

    # North Central
    'Anuradhapura': 'North Central', 'Polonnaruwa': 'North Central',

    # Uva
    'Badulla': 'Uva', 'Monaragala': 'Uva',

    # Sabaragamuwa
    'Ratnapura': 'Sabaragamuwa', 'Kegalle': 'Sabaragamuwa'
}

In [38]:
df_lf['PROVINCE'] = df_lf['DISTRICT'].map(district_to_province)
df_lf[['DISTRICT', 'PROVINCE','employment_status']].head(20)

    DISTRICT PROVINCE employment_status
1    Colombo  Western          Employed
15   Colombo  Western          Employed
20   Colombo  Western          Employed
29   Colombo  Western          Employed
48   Colombo  Western          Employed
49   Colombo  Western          Employed
55   Colombo  Western          Employed
56   Colombo  Western          Employed
76   Colombo  Western          Employed
83   Colombo  Western          Employed
84   Colombo  Western        Unemployed
111  Colombo  Western          Employed
114  Colombo  Western          Employed
128  Colombo  Western        Unemployed
133  Colombo  Western          Employed
169  Colombo  Western          Employed
175  Colombo  Western        Unemployed
192  Colombo  Western          Employed
201  Colombo  Western          Employed
207  Colombo  Western          Employed

In [43]:
df_lf.head()

,MONTH,SECTOR,DISTRICT,PSU,HUNIT,HHOLD,SERNO,SEX,BYEAR,BMONTH,...,Q4,Q6_A,Q47,Q48,Q50,Q51,Q52,employment_status,EDU_group,PROVINCE
1,1,Urban,Colombo,1,2,1,2,Male,1993,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed,G.C.E.(A/L),Western
15,1,Urban,Colombo,2,8,1,2,Female,1999,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed,Degree / Education institue,Western
20,1,Rural,Colombo,3,9,1,3,Male,2002,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed,G.C.E.(A/L),Western
29,1,Urban,Colombo,5,8,1,2,Male,1995,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed,G.C.E.(A/L),Western
48,1,Rural,Colombo,8,6,1,3,Male,1996,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Employed,Grade 6-10,Western

In [47]:
df_lf.to_csv("unemp_youth.csv", index=False)